# Generated by Django 3.2.8 on 2021-11-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20211125_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='room',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='room',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='room',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='teacher',
        ),
    ]
