# Generated by Django 3.2.8 on 2021-11-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20211126_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='is_submitted',
        ),
    ]
