# Generated by Django 3.2.8 on 2021-11-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20211126_0450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
